services:
  

  web:
    build: 
      context: ..
      dockerfile: project/Dockerfile
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/code
    ports:
      - "8000:8000"

    env_file:
      - .env

volumes:
  postgres_data:

